package com.jujin.freeway.db.internal;

import com.jujin.freeway.db.PooledConnection;
import com.jujin.freeway.db.util.SqlTextParser;

import com.jujin.freeway.db.BatchQuery;
import com.jujin.freeway.db.ExecuteResult;
import com.jujin.freeway.db.SqlException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

final class BatchQueryImpl implements BatchQuery {

    private static final Logger LOG = LoggerFactory.getLogger(
        BatchQueryImpl.class
    );
    private final DatabaseImpl db;
    private final PooledConnection boundConnection;
    private final long boundEpoch;
    private final String sql;
    private final SqlTextParser.Result parsed;
    private final boolean mayHaveGeneratedKeys;
    private final int positionalParameterCount;
    private List<Object[]> positionalRows = List.of();
    private List<Map<String, Object>> namedRows = List.of();

    BatchQueryImpl(
        DatabaseImpl db,
        PooledConnection boundConnection,
        String sql
    ) {
        this.db = db;
        this.boundConnection = boundConnection;
        this.boundEpoch = db.txEpoch();
        this.sql = sql;
        this.parsed = SqlTextParser.parseNamed(sql);
        this.mayHaveGeneratedKeys = DatabaseImpl.startsWithInsert(sql);
        this.positionalParameterCount =
            SqlTextParser.paramIndexes(parsed.sql()).size();
        SqlTextParser.requireNoMixedPlaceholders(sql);
    }

    @Override
    public BatchQuery rows(Object[]... rows) {
        this.positionalRows = rows == null
            ? List.of()
            : List.copyOf(Arrays.asList(rows));
        this.namedRows = List.of();
        return this;
    }

    @Override
    public BatchQuery rows(List<Object[]> rows) {
        this.positionalRows = rows == null ? List.of() : List.copyOf(rows);
        this.namedRows = List.of();
        return this;
    }

    @Override
    public BatchQuery named(List<Map<String, Object>> rows) {
        this.namedRows = rows == null ? List.of() : List.copyOf(rows);
        this.positionalRows = List.of();
        return this;
    }

    @Override
    public List<ExecuteResult> execute() {
        if (boundConnection != null) {
            db.checkBoundEpoch(boundEpoch);
        }
        boolean ownConnection = boundConnection == null;
        PooledConnection conn = ownConnection
            ? db.pool().borrow()
            : boundConnection;
        boolean autoCommitChanged = false;
        try {
            var raw = conn.connection();
            if (ownConnection || raw.getAutoCommit()) {
                raw.setAutoCommit(false);
                autoCommitChanged = true;
            }
            int autoGeneratedKeys = mayHaveGeneratedKeys
                ? Statement.RETURN_GENERATED_KEYS
                : Statement.NO_GENERATED_KEYS;
            try (
                PreparedStatement stmt = raw.prepareStatement(
                    parsed.sql(),
                    autoGeneratedKeys
                )
            ) {
                stmt.setQueryTimeout(db.queryTimeoutSeconds());
                if (!namedRows.isEmpty()) {
                    for (var row : namedRows) {
                        bindRow(stmt, row);
                        stmt.addBatch();
                    }
                } else {
                    for (var row : positionalRows) {
                        if (row.length != positionalParameterCount) {
                            throw new SqlException(
                                "Parameter count mismatch in batch SQL: " +
                                    sql +
                                    ". Expected " +
                                    positionalParameterCount +
                                    " value(s) per row but got " +
                                    row.length
                            );
                        }
                        stmt.clearParameters();
                        for (int i = 0; i < row.length; i++) {
                            stmt.setObject(i + 1, row[i]);
                        }
                        stmt.addBatch();
                    }
                }
                int[] counts = stmt.executeBatch();
                List<Long> ids = collectGeneratedKeys(stmt);

                List<ExecuteResult> results = new ArrayList<>(counts.length);
                for (int i = 0; i < counts.length; i++) {
                    Long id = i < ids.size() ? ids.get(i) : null;
                    results.add(new ExecuteResult(counts[i], id));
                }
                if (autoCommitChanged) {
                    raw.commit();
                }
                return results;
            } catch (SQLException e) {
                if (autoCommitChanged) {
                    rollbackQuietly(conn);
                }
                LOG.warn("Batch execution failed: {}", sql, e);
                throw new SqlException(
                    "Batch execution failed: " + e.getMessage(),
                    e
                );
            }
        } catch (SQLException e) {
            if (autoCommitChanged) {
                rollbackQuietly(conn);
            }
            LOG.warn("Batch execution failed: {}", sql, e);
            throw new SqlException(
                "Batch execution failed: " + e.getMessage(),
                e
            );
        } finally {
            if (autoCommitChanged) {
                restoreAutoCommitQuietly(conn);
            }
            if (ownConnection) {
                db.pool().release(conn);
            }
        }
    }

    private List<Long> collectGeneratedKeys(PreparedStatement stmt)
        throws SQLException {
        if (!mayHaveGeneratedKeys) {
            return List.of();
        }
        List<Long> ids = new ArrayList<>();
        try (ResultSet rs = stmt.getGeneratedKeys()) {
            while (rs.next()) {
                Object key = rs.getObject(1);
                if (key instanceof Number n) {
                    ids.add(n.longValue());
                }
            }
        }
        return ids;
    }

    private void rollbackQuietly(PooledConnection conn) {
        try {
            conn.connection().rollback();
        } catch (SQLException ignored) {}
    }

    private void restoreAutoCommitQuietly(PooledConnection conn) {
        try {
            conn.connection().setAutoCommit(true);
        } catch (SQLException ignored) {}
    }

    private void bindRow(PreparedStatement stmt, Map<String, Object> row)
        throws SQLException {
        for (String name : parsed.names()) {
            if (!row.containsKey(name)) {
                throw new SqlException(
                    "Missing value for named parameter '" +
                        name +
                        "' in batch SQL: " +
                        sql
                );
            }
        }
        for (String paramName : row.keySet()) {
            if (!parsed.names().contains(paramName)) {
                throw new SqlException(
                    "Unknown named parameter '" +
                        paramName +
                        "' in batch SQL: " +
                        sql
                );
            }
        }
        for (int i = 0; i < parsed.names().size(); i++) {
            stmt.setObject(i + 1, row.get(parsed.names().get(i)));
        }
    }
}
