package com.jujin.freeway.db;

import java.util.UUID;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AutoIncrementTest {

    @Test
    void insertReturnsAutoIncrementId() {
        var db = builder("auto_id_basic").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            var r1 = db.execute(SQL.insert("t_auto").set("label", "first"));
            assertEquals(1, r1.rows());
            assertTrue(r1.hasKey(), "INSERT should return a non-zero auto-increment ID");
            assertEquals(1L, r1.longKey(), "First inserted row should have ID = 1");

            var r2 = db.execute(SQL.insert("t_auto").set("label", "second"));
            assertEquals(2L, r2.longKey(), "Second inserted row should have ID = 2");
        }
    }

    @Test
    void insertReturnsGenuineGeneratedKey() {
        var db = builder("auto_id_verify").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            ExecuteResult result = db.execute("insert into t_auto (label) values (?)", "item");
            assertEquals(1, result.rows());
            assertTrue(result.hasKey(), "Raw INSERT should return generated keys");
            assertEquals(1L, result.longKey());

            Long selected = db.query("select id from t_auto where label = ?", "item")
                .one(Long.class).orElseThrow();
            assertEquals(1L, selected, "Auto-increment ID should match the database value");
        }
    }

    @Test
    void updateDoesNotReturnAutoIncrementId() {
        var db = builder("auto_id_update").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");
            db.execute("insert into t_auto (label) values ('original')");

            var r = db.execute("update t_auto set label = ? where id = ?", "modified", 1L);
            assertEquals(1, r.rows());
            assertFalse(r.hasKey(), "UPDATE should NOT return an auto-increment ID");
            assertEquals(0L, r.longKey(), "UPDATE's id() should be 0");
        }
    }

    @Test
    void updateNoMatchReturnsZeroRowsAndNoId() {
        var db = builder("auto_id_update_none").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            var r = db.execute("update t_auto set label = ? where id = ?", "x", 999L);
            assertEquals(0, r.rows());
            assertFalse(r.hasKey());
        }
    }

    @Test
    void deleteDoesNotReturnAutoIncrementId() {
        var db = builder("auto_id_delete").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");
            db.execute("insert into t_auto (label) values ('goner')");

            var r = db.execute("delete from t_auto where id = ?", 1L);
            assertTrue(r.rows() > 0, "DELETE should affect rows");
            assertFalse(r.hasKey(), "DELETE should NOT return an auto-increment ID");
            assertEquals(0L, r.longKey(), "DELETE's id() should be 0");
        }
    }

    @Test
    void insertWithSqlBuilderReturnsAutoIncrementId() {
        var db = builder("auto_id_builder").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            var r = db.execute(SQL.insert("t_auto").set("label", "builder-test"));
            assertEquals(1, r.rows());
            assertTrue(r.hasKey(), "SQL builder INSERT should return auto-increment ID");
            assertEquals(1L, r.longKey());
        }
    }

    @Test
    void insertInTransactionReturnsAutoIncrementId() {
        var db = builder("auto_id_tx").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            db.transaction(() -> {
                var r = db.execute(SQL.insert("t_auto").set("label", "tx-item"));
                assertEquals(1, r.rows());
                assertTrue(r.hasKey(), "INSERT in transaction should return auto-increment ID");
                assertEquals(1L, r.longKey());
            });

            Long count = db.query("select count(*) from t_auto").one(Long.class).orElseThrow();
            assertEquals(1L, count);
        }
    }

    @Test
    void rawInsertInTransactionReturnsAutoIncrementId() {
        var db = builder("auto_id_raw_tx").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            db.transaction(() -> {
                var r = db.execute("insert into t_auto (label) values (?)", "tx-item");
                assertEquals(1, r.rows());
                assertTrue(r.hasKey(), "Raw INSERT in transaction should return auto-increment ID");
                assertEquals(1L, r.longKey());
            });
        }
    }

    @Test
    void rawInsertWithLeadingCommentsReturnsAutoIncrementId() {
        var db = builder("auto_id_raw_comments").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            var r = db.execute("""
                /* create item */
                -- generated key should still be requested
                insert into t_auto (label) values (?)
                """, "commented");

            assertEquals(1, r.rows());
            assertTrue(r.hasKey());
            assertEquals(1L, r.longKey());
        }
    }

    @Test
    void insertWithExplicitPrimaryKeyReturnsId() {
        var db = builder("auto_id_explicit").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            var r = db.execute(SQL.insert("t_auto").set("id", 100L).set("label", "explicit"));
            assertEquals(1, r.rows());
            assertTrue(r.hasKey(), "INSERT with explicit PK should still return the generated keys value");
            assertEquals(100L, r.longKey());
        }
    }

    @Test
    void insertAndUpdateCombined() {
        var db = builder("auto_id_combined").build();
        try (db) {
            db.execute("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))");

            var insertResult = db.execute(SQL.insert("t_auto").set("label", "combo"));
            long newId = insertResult.longKey();
            assertTrue(insertResult.hasKey());
            assertTrue(newId > 0);

            var updateResult = db.execute("update t_auto set label = ? where id = ?", "combo-edited", newId);
            assertEquals(1, updateResult.rows());
            assertFalse(updateResult.hasKey());

            String label = db.query("select label from t_auto where id = ?", newId)
                .one(String.class).orElseThrow();
            assertEquals("combo-edited", label);
        }
    }

    private static DatabaseBuilder builder(String name) {
        return new DatabaseBuilder()
            .config(PoolConfig.defaults(
                "jdbc:h2:mem:" + name + UUID.randomUUID().toString().replace('-', '_')
                    + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa", ""));
    }
}
