package com.jujin.freeway.db;

import java.util.UUID;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * {@link Query#execute()} 自增 ID 返回功能集成测试。
 * <p>
 * 验证 INSERT 操作的 {@link ExecuteResult#id()} 正确返回数据库自增主键，
 * 且 UPDATE/DELETE 操作的 {@link ExecuteResult#hasId()} 返回 false。
 */
class AutoIncrementTest {

    @Test
    void insertReturnsAutoIncrementId() {
        var db = builder("auto_id_basic").build();
        try (db) {
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();

            var r1 = db.sql(SQL.insert("t_auto").set("label", "first")).execute();
            assertEquals(1, r1.rows());
            assertTrue(r1.hasId(), "INSERT should return a non-zero auto-increment ID");
            assertEquals(1L, r1.id(), "First inserted row should have ID = 1");

            var r2 = db.sql(SQL.insert("t_auto").set("label", "second")).execute();
            assertEquals(2L, r2.id(), "Second inserted row should have ID = 2");
        }
    }

    @Test
    void insertReturnsGenuineGeneratedKey() {
        var db = builder("auto_id_verify").build();
        try (db) {
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();

            db.sql("insert into t_auto (label) values (?)", "item").execute().id();

            // 用 SELECT 核实返回的 ID 确实是数据库实际写入的值
            Long selected = db.sql("select id from t_auto where label = ?", "item")
                .one(Long.class).orElseThrow();
            assertEquals(1L, selected, "Auto-increment ID should match the database value");
        }
    }

    @Test
    void updateDoesNotReturnAutoIncrementId() {
        var db = builder("auto_id_update").build();
        try (db) {
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();
            db.sql("insert into t_auto (label) values ('original')").execute();

            var r = db.sql("update t_auto set label = ? where id = ?", "modified", 1L).execute();
            assertEquals(1, r.rows());
            assertFalse(r.hasId(), "UPDATE should NOT return an auto-increment ID");
            assertEquals(0L, r.id(), "UPDATE's id() should be 0");
        }
    }

    @Test
    void updateNoMatchReturnsZeroRowsAndNoId() {
        var db = builder("auto_id_update_none").build();
        try (db) {
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();

            var r = db.sql("update t_auto set label = ? where id = ?", "x", 999L).execute();
            assertEquals(0, r.rows());
            assertFalse(r.hasId());
        }
    }

    @Test
    void deleteDoesNotReturnAutoIncrementId() {
        var db = builder("auto_id_delete").build();
        try (db) {
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();
            db.sql("insert into t_auto (label) values ('goner')").execute();

            var r = db.sql("delete from t_auto where id = ?", 1L).execute();
            assertTrue(r.rows() > 0, "DELETE should affect rows");
            assertFalse(r.hasId(), "DELETE should NOT return an auto-increment ID");
            assertEquals(0L, r.id(), "DELETE's id() should be 0");
        }
    }

    @Test
    void insertWithSqlBuilderReturnsAutoIncrementId() {
        var db = builder("auto_id_builder").build();
        try (db) {
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();

            var r = db.sql(
                SQL.insert("t_auto").set("label", "builder-test")
            ).execute();
            assertEquals(1, r.rows());
            assertTrue(r.hasId(), "SQL builder INSERT should return auto-increment ID");
            assertEquals(1L, r.id());
        }
    }

    @Test
    void insertInTransactionReturnsAutoIncrementId() {
        var db = builder("auto_id_tx").build();
        try (db) {
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();

            db.transaction(tx -> {
                var r = tx.sql(SQL.insert("t_auto").set("label", "tx-item")).execute();
                assertEquals(1, r.rows());
                assertTrue(r.hasId(), "INSERT in transaction should return auto-increment ID");
                assertEquals(1L, r.id());
            });

            // 验证事务已提交，数据确实写入
            Long count = db.sql("select count(*) from t_auto").one(Long.class).orElseThrow();
            assertEquals(1L, count);
        }
    }

    @Test
    void insertWithExplicitPrimaryKeyReturnsId() {
        var db = builder("auto_id_explicit").build();
        try (db) {
            // 使用 GENERATED BY DEFAULT AS IDENTITY 允许显式插入自定义 ID
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();

            var r = db.sql(SQL.insert("t_auto").set("id", 100L).set("label", "explicit")).execute();
            assertEquals(1, r.rows());
            assertTrue(r.hasId(), "INSERT with explicit PK should still return the generated keys value");
            // H2 在这种模式下返回的是实际插入的值 100
            assertEquals(100L, r.id());
        }
    }

    @Test
    void insertAndUpdateCombined() {
        var db = builder("auto_id_combined").build();
        try (db) {
            db.sql("create table t_auto (id bigint generated by default as identity primary key, label varchar(64))")
                .execute();

            // INSERT -> has id
            var insertResult = db.sql(SQL.insert("t_auto").set("label", "combo")).execute();
            long newId = insertResult.id();
            assertTrue(insertResult.hasId());
            assertTrue(newId > 0);

            // UPDATE -> no id
            var updateResult = db.sql("update t_auto set label = ? where id = ?", "combo-edited", newId).execute();
            assertEquals(1, updateResult.rows());
            assertFalse(updateResult.hasId());

            // 验证数据
            String label = db.sql("select label from t_auto where id = ?", newId)
                .one(String.class).orElseThrow();
            assertEquals("combo-edited", label);
        }
    }

    // ====================== 辅助 ======================

    private static DatabaseBuilder builder(String name) {
        return new DatabaseBuilder()
            .config(DatabaseConfig.defaults(
                "jdbc:h2:mem:" + name + UUID.randomUUID().toString().replace('-', '_')
                    + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa", ""));
    }
}
