package com.jujin.freeway.db;

import com.jujin.freeway.db.schema.*;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class OrmTest {

    // ==================== entity types ====================

    @Table
    record Post(@Id @Generated Long id, @Column String title, @Column String body) {
        Post(String title, String body) { this(null, title, body); }
    }

    @Table("comments")
    static class Comment {
        @Id @Generated Long id;
        @Column String text;
        @Column("post_id") Long postId;

        Comment() {}
        Comment(String text, Long postId) { this.text = text; this.postId = postId; }
    }

    @Table("app_user")
    static class User {
        @Id String username;
        @Column String email;
        @Transient String ignoredField;

        User() {}
        User(String username, String email) { this.username = username; this.email = email; }
    }

    @Test
    void ofWithCoercerUsesDatabaseDialect() {
        Database db = builder("orm_coercer").build();
        try (db) {
            Schema.ensure(db, Post.class);
            Orm orm = Orm.of(db, new com.jujin.freeway.commons.coercion.CoercerDefault());
            orm.insert(new Post("title", "body"));
            assertTrue(orm.findById(Post.class, 1L).isPresent(),
                "Orm.of(db, coercer) should derive the dialect from the database");
        }
    }

    // ==================== helpers ====================

    private static DatabaseBuilder builder(String name) {
        return new DatabaseBuilder()
            .config(PoolConfig.defaults(
                "jdbc:h2:mem:" + name + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", ""));
    }

    private static String uniqueDb(String prefix) {
        return "freeway_orm_" + prefix + "_" + UUID.randomUUID().toString().replace('-', '_');
    }

    // ==================== insert ====================

    @Test
    void insertRecordReturnsGeneratedId() {
        var db = builder(uniqueDb("insert_record")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);

            Post p = new Post("Hello", "World");
            var r = orm.insert(p);

            assertTrue(r.hasKey());
            assertTrue(r.longKey() > 0);
        }
    }

    @Test
    void insertWritesBackGeneratedIdToRecord() {
        var db = builder(uniqueDb("writeback")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);

            Post p = new Post("Hello", "World");
            var r = orm.insert(p);

            // records are immutable, id is on the result
            assertTrue(r.hasKey());
            assertEquals(1L, r.longKey());
        }
    }

    @Test
    void insertBean() {
        var db = builder(uniqueDb("insert_bean")).build();
        try (db) {
            db.execute("CREATE TABLE comments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, text VARCHAR(255), post_id BIGINT)");
            Orm orm = Orm.of(db);

            Comment c = new Comment("nice post", 1L);
            var r = orm.insert(c);

            assertTrue(r.hasKey());
            assertNotNull(c.id);
            assertTrue(c.id > 0);
        }
    }

    @Test
    void insertNonGeneratedId() {
        var db = builder(uniqueDb("nongen")).build();
        try (db) {
            db.execute("CREATE TABLE app_user (username VARCHAR(255) PRIMARY KEY, email VARCHAR(255))");
            Orm orm = Orm.of(db);

            User u = new User("alice", "alice@example.com");
            var r = orm.insert(u);

            assertEquals(1, r.rows());
        }
    }

    // ==================== find ====================

    @Test
    void findById() {
        var db = builder(uniqueDb("find")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);

            orm.insert(new Post("A", "body a"));
            orm.insert(new Post("B", "body b"));

            Post found = orm.findById(Post.class, 2L).orElseThrow();
            assertEquals("B", found.title());
            assertEquals("body b", found.body());
        }
    }

    @Test
    void findByIdNotFound() {
        var db = builder(uniqueDb("notfound")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);

            assertTrue(orm.findById(Post.class, 999L).isEmpty());
        }
    }

    @Test
    void findAll() {
        var db = builder(uniqueDb("findall")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);

            orm.insert(new Post("A", "a"));
            orm.insert(new Post("B", "b"));

            List<Post> posts = orm.findAll(Post.class);
            assertEquals(2, posts.size());
        }
    }

    // ==================== update ====================

    @Test
    void updateBean() {
        var db = builder(uniqueDb("update")).build();
        try (db) {
            db.execute("CREATE TABLE comments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, text VARCHAR(255), post_id BIGINT)");
            Orm orm = Orm.of(db);

            Comment c = new Comment("original", 1L);
            orm.insert(c);
            c.text = "updated";
            orm.update(c);

            Comment reloaded = orm.findById(Comment.class, c.id).orElseThrow();
            assertEquals("updated", reloaded.text);
        }
    }

    // ==================== delete ====================

    @Test
    void deleteEntity() {
        var db = builder(uniqueDb("delete")).build();
        try (db) {
            db.execute("CREATE TABLE comments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, text VARCHAR(255), post_id BIGINT)");
            Orm orm = Orm.of(db);

            Comment c = new Comment("text", 1L);
            orm.insert(c);
            orm.delete(c);

            assertTrue(orm.findById(Comment.class, c.id).isEmpty());
        }
    }

    @Test
    void deleteById() {
        var db = builder(uniqueDb("deleteById")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);

            orm.insert(new Post("x", "y"));
            orm.deleteById(Post.class, 1L);

            assertTrue(orm.findById(Post.class, 1L).isEmpty());
        }
    }

    // ==================== edge cases ====================

    @Test
    void updateWithoutIdThrows() {
        var db = builder(uniqueDb("noid_update")).build();
        try (db) {
            db.execute("CREATE TABLE comments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, text VARCHAR(255), post_id BIGINT)");
            Orm orm = Orm.of(db);

            Comment c = new Comment("text", 1L);
            assertThrows(SqlException.class, () -> orm.update(c));
        }
    }

    @Test
    void nonGeneratedIdIsPreserved() {
        var db = builder(uniqueDb("preserve")).build();
        try (db) {
            db.execute("CREATE TABLE app_user (username VARCHAR(255) PRIMARY KEY, email VARCHAR(255))");
            Orm orm = Orm.of(db);

            User u = new User("bob", "bob@example.com");
            orm.insert(u);
            User found = orm.findById(User.class, "bob").orElseThrow();

            assertEquals("bob", found.username);
            assertEquals("bob@example.com", found.email);
        }
    }

    // ==================== findAll ordering / limit / offset ====================

    @Test
    void findAllOrderedBy() {
        var db = builder(uniqueDb("ordered")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);
            orm.insert(new Post("C", "c"));
            orm.insert(new Post("A", "a"));
            orm.insert(new Post("B", "b"));

            List<Post> posts = orm.findAll(Post.class, "title ASC", 0, 0);
            assertEquals("A", posts.get(0).title());
            assertEquals("B", posts.get(1).title());
            assertEquals("C", posts.get(2).title());
        }
    }

    @Test
    void findAllWithLimit() {
        var db = builder(uniqueDb("limit")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);
            orm.insert(new Post("A", "a"));
            orm.insert(new Post("B", "b"));
            orm.insert(new Post("C", "c"));

            List<Post> posts = orm.findAll(Post.class, "id ASC", 2, 0);
            assertEquals(2, posts.size());
        }
    }

    @Test
    void findAllWithOffset() {
        var db = builder(uniqueDb("offset")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);
            orm.insert(new Post("A", "a"));
            orm.insert(new Post("B", "b"));
            orm.insert(new Post("C", "c"));

            List<Post> posts = orm.findAll(Post.class, "id ASC", 0, 1);
            assertEquals(2, posts.size());
            assertEquals("B", posts.get(0).title());
            assertEquals("C", posts.get(1).title());
        }
    }

    // ==================== save (upsert) ====================

    @Test
    void saveInsertsWhenIdIsNull() {
        var db = builder(uniqueDb("save_insert")).build();
        try (db) {
            db.execute("CREATE TABLE comments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, text VARCHAR(255), post_id BIGINT)");
            Orm orm = Orm.of(db);

            Comment c = new Comment("hello", 1L);
            orm.save(c);
            assertNotNull(c.id);
            assertEquals(1L, (long) c.id);
        }
    }

    @Test
    void saveReturnsGeneratedId() {
        var db = builder(uniqueDb("save_id")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT)");
            Orm orm = Orm.of(db);

            Post p = new Post("Hello", "World");
            var r = orm.save(p);
            assertTrue(r.hasKey());
        }
    }

    // ==================== explicit columns (not SELECT *) ====================

    @Test
    void handlesExtraColumnInTable() {
        var db = builder(uniqueDb("extra_col")).build();
        try (db) {
            db.execute("CREATE TABLE post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255), body TEXT, hidden VARCHAR(255) DEFAULT 'x')");
            Orm orm = Orm.of(db);

            Post p = new Post("A", "body");
            orm.insert(p);

            Post found = orm.findById(Post.class, 1L).orElseThrow();
            assertEquals("A", found.title());
            // hidden column not in the entity — SELECT only lists known columns
        }
    }
}
