package com.jujin.freeway.db.dialect;

import com.jujin.freeway.db.Database;
import java.util.Set;
import java.util.Locale;

/**
 * PostgreSQL / H2 (PostgreSQL compatibility mode) SQL dialect.
 *
 * <p>Uses double-quote identifier quoting, {@code GENERATED BY DEFAULT AS IDENTITY}
 * for auto-increment, and queries {@code INFORMATION_SCHEMA} /
 * {@code pg_indexes} for schema introspection.
 */
public class PostgresDialect implements Dialect {

    private static final Set<String> RESERVED = Dialect.buildReserved(
        "window", "lateral", "both", "leading", "trailing", "placing", "symmetric",
        "variadic", "current_user", "session_user", "localtime", "localtimestamp"
    );

    @Override
    public String dialectId() {
        return "postgresql";
    }

    @Override
    public String truncateTable(String tableName) {
        return "TRUNCATE TABLE " + quoteName(tableName) + " RESTART IDENTITY";
    }

    /**
     * Drops with {@code CASCADE}, which is intentional: dependent foreign-key
     * constraints and views referencing the table are dropped too. {@code Schema}
     * appends the clause declared here.
     */
    @Override
    public boolean dropTableCascade() {
        return true;
    }

    @Override
    public String generatedClause() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    /**
     * Offset without LIMIT. PostgreSQL accepts {@code LIMIT ALL}, but this
     * dialect also serves H2 in PostgreSQL compatibility mode (which rejects
     * {@code LIMIT ALL} and caps {@code LIMIT} at a 32-bit int), so emit
     * {@code LIMIT 2147483647 OFFSET n} — valid on both.
     */
    @Override
    public String offsetOnlyClause(long offset) {
        return "LIMIT 2147483647 OFFSET " + offset;
    }

    // ====================== SQL lexing ======================

    @Override
    public boolean dollarQuoting() {
        return true;
    }

    @Override
    public boolean escapeStringPrefix() {
        return true;
    }

    @Override
    public String defaultUUIDType() {
        return "UUID";
    }

    // ====================== schema introspection ======================

    @Override
    public Set<String> existingTables(Database db) {
        return querySet(db,
            "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE UPPER(TABLE_SCHEMA) = UPPER(?) AND TABLE_TYPE = 'BASE TABLE'",
            effectiveSchema());
    }

    @Override
    public Set<String> existingColumns(Database db, String tableName) {
        return querySet(db,
            "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE UPPER(TABLE_NAME) = ? AND UPPER(TABLE_SCHEMA) = UPPER(?)",
            tableName.toUpperCase(Locale.ROOT), effectiveSchema());
    }

    @Override
    public Set<String> existingIndexes(Database db, String tableName) {
        return querySet(db,
            "SELECT indexname FROM pg_indexes WHERE schemaname = ? AND tablename = ?",
            effectiveSchema(), tableName.toLowerCase(Locale.ROOT));
    }

    @Override
    public Set<String> reservedWords() {
        return RESERVED;
    }
}
