<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jujin8.freeway</groupId>
        <artifactId>freeway-parent</artifactId>
        <version>1.0.3</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>freeway-starter-web</artifactId>
    <packaging>jar</packaging>

    <name>Freeway :: Starter :: Web</name>
    <description>Web application starter for freeway with the default Robaho engine.</description>

    <dependencies>
        <dependency>
            <groupId>com.jujin8.freeway</groupId>
            <artifactId>freeway-starter-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jujin8.freeway</groupId>
            <artifactId>freeway-http</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jujin8.freeway</groupId>
            <artifactId>freeway-http-robaho</artifactId>
        </dependency>
    </dependencies>
</project>
