package demo;

import com.jujin.freeway.db.schema.Column;
import com.jujin.freeway.db.schema.Generated;
import com.jujin.freeway.db.schema.Id;
import com.jujin.freeway.db.schema.Table;

/**
 * The entity: a record with schema annotations; {@code schema.auto} (on by
 * default) creates the table before HTTP starts. Mapped to {@code t_user}
 * because {@code user} is a reserved word.
 */
@Table("t_user")
public record User(
    @Id @Generated Long id,
    @Column String name,
    @Column Integer age
) {
    /** Constructor for inserts: the id is generated by the database. */
    public User(String name, Integer age) {
        this(null, name, age);
    }
}
