package com.jujin.freeway.http.engine;
import java.io.ByteArrayOutputStream; import java.io.IOException; import java.io.OutputStream; import java.util.*;
final class HPackContext { private final List<Http2HeaderField> dyn=new ArrayList<>(1024);
public Http2HeaderField get(int i){if(i>0&&i<=61)return StaticTable.get(i);int d=i-62;return d>=0&&d<dyn.size()?dyn.get(d):null;}
public List<Http2HeaderField> decode(byte[]b)throws IOException{var f=new ArrayList<Http2HeaderField>(8);int p=0;while(p<b.length){var h=new Http2HeaderField();if((b[p]&0x80)!=0)p=decodeIdx(b,p,h);else if((b[p]&0x40)!=0){p=decodeInc(b,p,h);dyn.addFirst(h);}else if((b[p]&0xF0)==0)p=decodeWo(b,p,h);else if((b[p]&0xF0)==0x10)p=decodeNv(b,p,h);else if((b[p]&0xE0)==0x20){if(!f.isEmpty())throw new Http2Exception(Http2ErrorCode.COMPRESSION_ERROR);p=decodeSz(b,p);continue;}else throw new Http2Exception(Http2ErrorCode.COMPRESSION_ERROR);f.add(h);}return f;}
private int decodeIdx(byte[]b,int p,Http2HeaderField h)throws IOException{var r=readInt(b,p,7);var f=get(r.v);if(f==null)throw new Http2Exception(Http2ErrorCode.COMPRESSION_ERROR);h.name=f.name;h.normalizedName=f.normalizedName;h.value=f.value;return r.i;}
private int decodeInc(byte[]b,int p,Http2HeaderField h)throws IOException{var r=readInt(b,p,6);p=decodeName(b,r.i,r.v,h);return decodeValue(b,p,h);}
private int decodeWo(byte[]b,int p,Http2HeaderField h)throws IOException{var r=readInt(b,p,4);p=decodeName(b,r.i,r.v,h);return decodeValue(b,p,h);}
private int decodeNv(byte[]b,int p,Http2HeaderField h)throws IOException{var r=readInt(b,p,4);p=decodeName(b,r.i,r.v,h);return decodeValue(b,p,h);}
private int decodeSz(byte[]b,int p)throws IOException{var r=readInt(b,p,5);if(r.v>4096)throw new Http2Exception(Http2ErrorCode.COMPRESSION_ERROR);while(dyn.size()>r.v)dyn.removeLast();return r.i;}
private int decodeName(byte[]b,int p,int idx,Http2HeaderField h)throws IOException{if(idx==0){boolean hf=(b[p]&0x80)!=0;int l=b[p]&0x7F;p++;String n=hf?Huffman.decode(b,p,l):new String(b,p,l);if(!n.equals(n.toLowerCase()))throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);h.name=n;h.normalizedName=Http2HeaderField.normalize(n);return p+l;}var f=get(idx);if(f==null)throw new Http2Exception(Http2ErrorCode.COMPRESSION_ERROR);h.name=f.name;h.normalizedName=f.normalizedName;return p;}
private int decodeValue(byte[]b,int p,Http2HeaderField h)throws IOException{boolean hf=(b[p]&0x80)!=0;var r=readInt(b,p,7);h.value=hf?Huffman.decode(b,r.i,r.v):new String(b,r.i,r.v);return r.i+r.v;}
private record IntR(int i,int v){}
static IntR readInt(byte[]b,int p,int bits){int m=(1<<bits)-1;int v=b[p]&m;p++;if(v<m)return new IntR(p,v);int s=0,x;do{x=b[p]&0xFF;v+=(x&0x7F)<<s;s+=7;p++;}while((x&0x80)!=0);return new IntR(p,v);}
public void writeResponseHeaders(Map<String,List<String>> h,OutputStream o,int sid,boolean es)throws IOException{var bo=new ByteArrayOutputStream(256);bo.write(encodeLit(":status",h.getOrDefault(":status",List.of("200")).getFirst()));for(var e:h.entrySet()){if(e.getKey().startsWith(":"))continue;String k=Character.toLowerCase(e.getKey().charAt(0))+e.getKey().substring(1);for(String v:e.getValue())bo.write(encodeLit(k,v));}var fl=es?FrameFlag.FlagSet.of(FrameFlag.END_HEADERS,FrameFlag.END_STREAM):FrameFlag.FlagSet.of(FrameFlag.END_HEADERS);FrameHeader.writeTo(o,bo.size(),FrameType.HEADERS,fl,sid);bo.writeTo(o);}
private static byte[] encodeLit(String n,String v){if(":status".equals(n)){byte[] ix=StaticTable.statusIndex(v);if(ix!=null)return ix;}Integer ix=StaticTable.nameIndex(n);byte[]pf=ix!=null?encodeIntVal(ix,4):encodeIntVal(0,4);byte[]nb=ix!=null?null:encodeStr(n.getBytes());byte[]vb=encodeStr(v.getBytes());return nb==null?BinUtils.combine(new byte[][]{pf,vb}):BinUtils.combine(new byte[][]{pf,nb,vb});}
static byte[] encodeIntVal(int v,int bits){int m=(1<<bits)-1;if(v<m)return new byte[]{(byte)v};byte[]b=new byte[]{(byte)m};v-=m;while(v>=128){b=Arrays.copyOf(b,b.length+1);b[b.length-1]=(byte)((v&0x7F)|0x80);v>>>=7;}b=Arrays.copyOf(b,b.length+1);b[b.length-1]=(byte)v;return b;}
static byte[] encodeStr(byte[]v){int l=v.length;if(l<128){byte[]b=new byte[1+l];b[0]=(byte)l;System.arraycopy(v,0,b,1,l);return b;}byte[]b=new byte[2+l];b[0]=(byte)(l|0x80);b[1]=(byte)(l>>7);System.arraycopy(v,0,b,2,l);return b;}
}
