package com.jujin.freeway.http.engine;
import com.jujin.freeway.http.engine.BufferedOutputStream;
import java.io.*; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.*; import java.util.concurrent.locks.LockSupport;
import org.slf4j.*;
final class Http2Stream { private static final Logger LOG=LoggerFactory.getLogger(Http2Stream.class); private static final FrameFlag.FlagSet END_STREAM=FrameFlag.FlagSet.of(FrameFlag.END_STREAM);
private final int sid,initWin,maxFrame; private final Http2Connection conn; private final Map<String,List<String>> reqH; private final Map<String,List<String>> respH=new LinkedHashMap<>(16); private final DataIn dataIn; private final OutputStream os; private final Http2Connection.StreamHandler handler;
public final AtomicLong sendWindow=new AtomicLong(65535); private final AtomicLong recvWindow=new AtomicLong(65535);
private volatile Thread thread; private volatile boolean open=true,halfClosed,outClosed; private final AtomicBoolean handling=new AtomicBoolean(),hSent=new AtomicBoolean(); private long inSize;
Http2Stream(int id,Http2Connection c,Map<String,List<String>> rh,Http2Connection.StreamHandler h){sid=id;conn=c;reqH=rh;handler=h;dataIn=new DataIn();var rw=conn.remoteSettings().get(SettingIdentifier.SETTINGS_INITIAL_WINDOW_SIZE);if(rw!=null)sendWindow.set((int)rw.value);var lw=conn.localSettings().get(SettingIdentifier.SETTINGS_INITIAL_WINDOW_SIZE);initWin=lw!=null?(int)lw.value:65535;if(lw!=null)recvWindow.set((int)lw.value);var mfs=conn.remoteSettings().get(SettingIdentifier.SETTINGS_MAX_FRAME_SIZE);maxFrame=mfs!=null?(int)mfs.value:16384;os=new BufferedOutputStream(new H2Out(sid));}
public boolean isOpen(){return open;} public boolean isHalfClosed(){return halfClosed;} public Map<String,List<String>> requestHeaders(){return reqH;} public Map<String,List<String>> responseHeaders(){return respH;}
public void close(){open=false;try{dataIn.close();os.close();}catch(IOException ignored){}var t=thread;if(t!=null)t.interrupt();}
public void dispatch(BaseFrame f,ExecutorService e)throws IOException{switch(f.header().type()){case HEADERS,CONTINUATION->{if(halfClosed)throw new Http2Exception(Http2ErrorCode.STREAM_CLOSED);halfClosed=f.header().flags().contains(FrameFlag.END_STREAM);start(e);}case DATA->{var df=(DataFrame)f;if(halfClosed)throw new Http2Exception(Http2ErrorCode.STREAM_CLOSED);if(!open)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);dataIn.enqueue(df.body);inSize+=df.body.length;if(df.header().flags().contains(FrameFlag.END_STREAM)){halfClosed=true;dataIn.wakeup();}}case RST_STREAM->{halfClosed=true;close();}case WINDOW_UPDATE->{int inc=((WindowUpdateFrame)f).increment();if(sendWindow.addAndGet(inc)>Integer.MAX_VALUE){conn.sendResetStream(Http2ErrorCode.FLOW_CONTROL_ERROR,sid);close();}}default->{}}}
public void writeResponseHeaders(boolean cs)throws IOException{if(!hSent.compareAndSet(false,true))return;conn.lock();try{conn.hpack().writeResponseHeaders(respH,conn.outputStream(),sid,cs);if(cs)outClosed=true;}finally{conn.unlock();}}
private void start(ExecutorService e)throws IOException{if(!handling.compareAndSet(false,true))throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);conn.requestsInProgress.incrementAndGet();InputStream i=halfClosed?InputStream.nullInputStream():dataIn;e.execute(()->{thread=Thread.currentThread();try{handler.handle(this,i,os,reqH);}catch(IOException ex){LOG.debug("H2 stream IO error",ex);close();}});}
private class H2Out extends OutputStream{private final int id;private boolean c;H2Out(int i){id=i;}public void write(int b)throws IOException{write(new byte[]{(byte)b});}public void write(byte[]b)throws IOException{write(b,0,b.length);}public void write(byte[]b,int o,int l)throws IOException{while(sendWindow.get()<=0&&!conn.isClosed())LockSupport.parkNanos(TimeUnit.MILLISECONDS.toNanos(1));writeResponseHeaders(false);if(outClosed)throw new IOException("output closed");while(l>0){int m=(int)Math.min(Math.min(l,maxFrame),Math.min(conn.sendWindow.get(),sendWindow.get()));if(m<=0){conn.lock();try{conn.outputStream().flush();}finally{conn.unlock();}LockSupport.parkNanos(TimeUnit.MILLISECONDS.toNanos(1));if(conn.isClosed())throw new IOException("closed");continue;}if(conn.sendWindow.addAndGet(-m)<0){conn.sendWindow.addAndGet(m);continue;}conn.lock();try{FrameHeader.writeTo(conn.outputStream(),m,FrameType.DATA,FrameFlag.NONE,id);conn.outputStream().write(b,o,m);}finally{conn.unlock();}o+=m;l-=m;sendWindow.addAndGet(-m);}}public void close()throws IOException{if(c)return;try{if(conn.isClosed()){hSent.compareAndSet(false,true);return;}writeResponseHeaders(false);conn.lock();try{if(!outClosed)FrameHeader.writeTo(conn.outputStream(),0,FrameType.DATA,END_STREAM,id);if(conn.requestsInProgress.decrementAndGet()==0)conn.outputStream().flush();}finally{conn.unlock();}dataIn.close();}finally{c=true;Http2Stream.this.close();}}}
private class DataIn extends InputStream{private final ConcurrentLinkedQueue<byte[]> q=new ConcurrentLinkedQueue<>();private volatile Thread r;private int o;void enqueue(byte[]d){q.add(d);LockSupport.unpark(r);}void wakeup(){LockSupport.unpark(r);}public void close()throws IOException{if(Thread.currentThread()==r||r==null){byte[]b=new byte[2048];while(read(b,0,b.length)!=-1);}else LockSupport.unpark(r);}public int read()throws IOException{byte[]b=new byte[1];return read(b,0,1)==-1?-1:b[0]&0xFF;}public int read(byte[]b,int off,int len)throws IOException{int t=0;try{r=Thread.currentThread();while(len>0){byte[]d;while((d=q.peek())==null){if(t>0)return t;if(halfClosed)return-1;LockSupport.park();if(Thread.interrupted())throw new IOException("interrupted");}int a=d.length-o,n=Math.min(len,a);System.arraycopy(d,o,b,off,n);o+=n;off+=n;len-=n;t+=n;if(o==d.length){q.poll();o=0;}}return t;}finally{if(t>0&&recvWindow.addAndGet(-t)<initWin/2){recvWindow.addAndGet(initWin/2);conn.lock();try{new WindowUpdateFrame(sid,initWin/2).writeTo(conn.outputStream());}finally{conn.unlock();}}}}}
}
