package com.jujin.freeway.http.engine;
import java.io.*; import java.net.*; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.*; import java.util.concurrent.locks.ReentrantLock;
import org.slf4j.*;
final class Http2Connection { private static final Logger LOG=LoggerFactory.getLogger(Http2Connection.class);
public static final String PREFACE="PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"; public static final String PARTIAL_PREFACE="\r\nSM\r\n\r\n";
private static final int DEF_WIN=65535,DEF_MAX_FRAME=16384;
private final InputStream in; private final OutputStream out; private final Socket socket; private final ExecutorService exec; private final StreamHandler handler; private final HPackContext hpack=new HPackContext();
private final ConcurrentHashMap<Integer,Http2Stream> streams=new ConcurrentHashMap<>(); private final SettingsMap remoteS=new SettingsMap(),localS=new SettingsMap();
public final AtomicLong sendWindow=new AtomicLong(DEF_WIN); public final AtomicInteger receiveWindow=new AtomicInteger(DEF_WIN),requestsInProgress=new AtomicInteger();
private final int connWin=DEF_WIN; private int maxStreams=-1,lastSeen,highWater; private final ReentrantLock lock=new ReentrantLock(); private final AtomicBoolean closed=new AtomicBoolean();
Http2Connection(Socket socket,InputStream i,OutputStream o,ExecutorService e,StreamHandler h){this.socket=socket;in=i;out=o;exec=e;handler=h;localS.set(new SettingParameter(SettingIdentifier.SETTINGS_MAX_FRAME_SIZE,DEF_MAX_FRAME));localS.set(new SettingParameter(SettingIdentifier.SETTINGS_INITIAL_WINDOW_SIZE,DEF_WIN));}
void lock(){lock.lock();} void unlock(){lock.unlock();} boolean isClosed(){return closed.get();} SettingsMap remoteSettings(){return remoteS;} SettingsMap localSettings(){return localS;} OutputStream outputStream(){return out;} HPackContext hpack(){return hpack;}
void close(){if(!closed.compareAndSet(false,true))return;for(var s:streams.values())s.close();try{socket.close();}catch(IOException ignored){}}
boolean hasProperPreface(boolean ssl)throws IOException{String m=ssl?PREFACE:PARTIAL_PREFACE;byte[]b=new byte[m.length()];FrameSerializer.readFully(in,b);return m.equals(new String(b));}
void writeFrame(List<byte[]>p)throws IOException{lock.lock();try{for(var x:p)out.write(x);out.flush();}finally{lock.unlock();}}
void handle()throws IOException{try{processFrames();}catch(Http2Exception e){LOG.debug("H2 error",e);sendGoAway(e.errorCode());throw e;}}
private void processFrames()throws IOException{boolean inH=false;int openSid=0;var frags=new ArrayList<byte[]>();
while(!closed.get()){var f=FrameSerializer.deserialize(in);int sid=f.header().streamId();if(sid!=0&&sid%2==0)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);
switch(f.header().type()){case SETTINGS->{if(f.header().flags().contains(FrameFlag.ACK)){maxStreams=streams.size()+Integer.MAX_VALUE;continue;}updateRemote((SettingsFrame)f);sendSettingsAck();continue;}case GOAWAY->{var gf=(GoawayFrame)f;if(gf.errorCode!=Http2ErrorCode.NO_ERROR)throw new IOException("GOAWAY");continue;}case PING->{if(!f.header().flags().contains(FrameFlag.ACK))sendPingAck((PingFrame)f);continue;}case WINDOW_UPDATE->{if(sid==0){int inc=((WindowUpdateFrame)f).increment();if(sendWindow.addAndGet(inc)>Integer.MAX_VALUE)throw new Http2Exception(Http2ErrorCode.FLOW_CONTROL_ERROR);continue;}}case NOT_IMPLEMENTED->{if(inH)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);if(sid==0)continue;}case DATA->{var df=(DataFrame)f;if(receiveWindow.addAndGet(-df.body.length)<connWin/10)sendConnWinUpdate();if(inH)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);}case HEADERS->{if(inH)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);if(sid<lastSeen)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);var ex=streams.get(sid);if(ex!=null){if(!ex.isOpen()||ex.isHalfClosed())throw new Http2Exception(Http2ErrorCode.STREAM_CLOSED);throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);}var hf2=(HeadersFrame)f;frags.add(hf2.headerBlock());if(!hf2.header().flags().contains(FrameFlag.END_HEADERS)){inH=true;openSid=sid;continue;}}case CONTINUATION->{if(inH&&sid!=openSid)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);if(!inH)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);var cf2=(ContinuationFrame)f;frags.add(cf2.headerBlock());if(!cf2.header().flags().contains(FrameFlag.END_HEADERS))continue;}case PRIORITY->{if(inH)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);if(sid==0)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);continue;}case RST_STREAM->{var rf2=(ResetStreamFrame)f;if(rf2.errorCode==Http2ErrorCode.NO_ERROR)continue;if(sid==0)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);if(streams.get(sid)==null&&sid>lastSeen)throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);}}
var target=streams.get(sid);
if(target==null&&lastSeen<sid){int cur=streams.size();if(maxStreams!=-1&&cur>=maxStreams)throw new Http2Exception(Http2ErrorCode.REFUSED_STREAM);highWater=Math.max(highWater,cur);byte[]block=BinUtils.combine(frags);var fields=new HeaderFields();for(var fld:hpack.decode(block))fields.add(fld);fields.validate();Map<String,List<String>> rh=new LinkedHashMap<>(fields.size()*2);for(var ff:fields.fields()){if(ff.value!=null)rh.computeIfAbsent(ff.normalizedName,k->new ArrayList<>(4)).add(ff.value);}frags.clear();inH=false;target=new Http2Stream(sid,this,rh,handler);streams.put(sid,target);lastSeen=sid;}else if(target==null){if(sid<=lastSeen){if(f.header().type()==FrameType.WINDOW_UPDATE)continue;throw new Http2Exception(Http2ErrorCode.STREAM_CLOSED);}throw new Http2Exception(Http2ErrorCode.PROTOCOL_ERROR);}
target.dispatch(f,exec);}}
private void updateRemote(SettingsFrame sf)throws IOException{for(var p:sf.params){long ow=remoteS.getOrDefault(SettingIdentifier.SETTINGS_INITIAL_WINDOW_SIZE,SettingParameter.DEFAULT_INITIAL_WINDOW_SIZE).value;if(p.identifier==SettingIdentifier.SETTINGS_INITIAL_WINDOW_SIZE){if(p.value>Integer.MAX_VALUE)throw new Http2Exception(Http2ErrorCode.FLOW_CONTROL_ERROR);for(var s:streams.values())s.sendWindow.addAndGet(p.value-ow);}remoteS.set(p);}}
public void sendMySettings()throws IOException{var sf=new SettingsFrame(new FrameHeader(0,FrameType.SETTINGS,FrameFlag.NONE,0));localS.forEach(sf.params::add);writeFrame(List.of(sf.encode()));}
private void sendSettingsAck()throws IOException{writeFrame(List.of(FrameHeader.encode(0,FrameType.SETTINGS,FrameFlag.FlagSet.of(FrameFlag.ACK),0)));}
private void sendConnWinUpdate()throws IOException{int cur=receiveWindow.get();int inc=connWin-cur;receiveWindow.addAndGet(inc);writeFrame(List.of(new WindowUpdateFrame(0,inc).encode()));}
public void sendGoAway(Http2ErrorCode c)throws IOException{lock.lock();try{new GoawayFrame(c,lastSeen).writeTo(out);out.flush();}finally{lock.unlock();}}
public void sendResetStream(Http2ErrorCode c,int sid)throws IOException{writeFrame(List.of(new ResetStreamFrame(c,sid).encode()));}
private void sendPingAck(PingFrame pf)throws IOException{writeFrame(List.of(new PingFrame(pf).encode()));}
InetSocketAddress remoteAddress(){return (InetSocketAddress)socket.getRemoteSocketAddress();} InetSocketAddress localAddress(){return (InetSocketAddress)socket.getLocalSocketAddress();}
@FunctionalInterface public interface StreamHandler{void handle(Http2Stream s,InputStream i,OutputStream o,Map<String,List<String>> h)throws IOException;}
}
