package com.jujin.freeway.db.dialect;

import java.util.List;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Direct syntax-surface tests for the four built-in dialects — the pieces
 * that need no live {@code Database} (identifier quoting, lexing flags, DDL
 * fragments, DML clauses). Introspection queries ({@code existingTables} &amp;
 * co.) are covered indirectly by the H2-backed schema/migration tests.
 */
class DialectSyntaxTest {

    private final PostgresDialect postgres = new PostgresDialect();
    private final MySqlDialect mysql = new MySqlDialect();
    private final SqliteDialect sqlite = new SqliteDialect();
    private final H2Dialect h2 = new H2Dialect();

    @Test
    void dialectIdsAreStableAndDistinct() {
        assertEquals("postgresql", postgres.dialectId());
        assertEquals("mysql", mysql.dialectId());
        assertEquals("sqlite", sqlite.dialectId());
        assertEquals("h2", h2.dialectId());
    }

    @Test
    void identifierQuotingContract() {
        // Reserved words are quoted; the dialect's own quote char is used.
        assertEquals("\"select\"", postgres.quoteName("select"));
        assertEquals("\"select\"", h2.quoteName("select"));
        assertEquals("`select`", mysql.quoteName("select"));
        assertEquals("\"select\"", sqlite.quoteName("select"));
        // Plain lowercase identifiers pass through untouched.
        assertEquals("plain_name", postgres.quoteName("plain_name"));
        // Uppercase forces quoting (case preservation).
        assertEquals("\"FirstName\"", postgres.quoteName("FirstName"));
        // Non-letter first character forces quoting.
        assertEquals("\"1abc\"", postgres.quoteName("1abc"));
        assertFalse(postgres.needsQuoting(null));
        assertFalse(postgres.needsQuoting("plain_name"));
        assertTrue(postgres.needsQuoting("user"));      // COMMON_RESERVED
        assertTrue(postgres.needsQuoting("ORDER"));     // case-insensitive match
        // Every dialect's reserved set includes the common words.
        for (Dialect d : new Dialect[] {postgres, mysql, sqlite, h2}) {
            assertTrue(d.reservedWords().containsAll(Dialect.COMMON_RESERVED), d.dialectId());
        }
    }

    @Test
    void dialectSpecificReservedWords() {
        assertTrue(postgres.needsQuoting("window"));
        assertTrue(mysql.needsQuoting("status"));
        assertTrue(sqlite.needsQuoting("abort"));
        assertTrue(h2.needsQuoting("dual"));
    }

    @Test
    void quotingAndLexingFlags() {
        // MySQL: backtick generation, backtick+double-quote accepted input,
        // # line comments and backslash string escapes.
        assertEquals('`', mysql.quoteChar());
        assertEquals("\"`", mysql.identifierQuoteChars());
        assertTrue(mysql.hashLineComments());
        assertTrue(mysql.backslashEscapesStrings());
        assertFalse(mysql.dollarQuoting());
        assertFalse(mysql.escapeStringPrefix());
        // PostgreSQL/H2: ANSI quotes; H2 additionally accepts backticks.
        assertEquals('"', postgres.quoteChar());
        assertEquals("\"", postgres.identifierQuoteChars());
        assertTrue(postgres.dollarQuoting());
        assertTrue(postgres.escapeStringPrefix());
        assertEquals("\"`", h2.identifierQuoteChars());
        // SQLite: ANSI quotes plus backticks on input.
        assertEquals("\"`", sqlite.identifierQuoteChars());
    }

    @Test
    void postgresFamilyDdlAndClauses() {
        for (Dialect d : new Dialect[] {postgres, h2}) {
            // Reserved-word table/column names exercise the quoting path.
            assertEquals("TRUNCATE TABLE \"order\" RESTART IDENTITY", d.truncateTable("order"), d.dialectId());
            assertTrue(d.dropTableCascade(), d.dialectId());
            assertEquals("GENERATED BY DEFAULT AS IDENTITY", d.generatedClause(), d.dialectId());
            assertEquals("LIMIT 2147483647 OFFSET 5", d.offsetOnlyClause(5), d.dialectId());
            assertEquals("UUID", d.defaultUUIDType(), d.dialectId());
            assertEquals(" ON CONFLICT (\"order\") DO UPDATE SET \"key\" = EXCLUDED.\"key\"",
                d.upsertClause(List.of("order"), List.of("key")), d.dialectId());
            assertTrue(d.supportsOnConflict(), d.dialectId());
            assertTrue(d.supportsReturning(), d.dialectId());
            assertTrue(d.supportsIndexIfNotExists(), d.dialectId());
            assertTrue(d.supportsTransactionalDdl(), d.dialectId());
            assertFalse(d.generatedPrimaryKeyInline(), d.dialectId());
            assertEquals("FOR UPDATE", d.forUpdateClause(), d.dialectId());
        }
        assertEquals("h2", h2.dialectId());
        assertEquals("BINARY VARYING", h2.defaultBinaryType());
        assertTrue(h2.needsQuoting("dual"));
        assertTrue(h2.needsQuoting("array"));
    }

    @Test
    void mysqlSqliteSpecialCases() {
        // MySQL: no ON CONFLICT/RETURNING, VALUES() upsert syntax, no
        // transactional DDL (implicit commit per statement).
        assertEquals(" ON DUPLICATE KEY UPDATE `key` = VALUES(`key`)",
            mysql.upsertClause(List.of("order"), List.of("key")));
        assertFalse(mysql.supportsOnConflict());
        assertFalse(mysql.supportsReturning());
        assertFalse(mysql.supportsIndexIfNotExists());
        assertFalse(mysql.supportsTransactionalDdl());
        assertEquals("LIMIT 18446744073709551615 OFFSET 5", mysql.offsetOnlyClause(5));
        assertEquals("AUTO_INCREMENT", mysql.generatedClause());
        assertEquals("DATETIME(6)", mysql.defaultInstantType());
        assertEquals("LONGBLOB", mysql.defaultBinaryType());
        assertEquals("TRUNCATE TABLE `order`", mysql.truncateTable("order"));

        // SQLite: no TRUNCATE, no row locks; inline generated PK; ADD COLUMN
        // NOT NULL unsupported.
        assertEquals("DELETE FROM \"order\"", sqlite.truncateTable("order"));
        assertEquals("", sqlite.forUpdateClause());
        assertEquals("LIMIT -1 OFFSET 5", sqlite.offsetOnlyClause(5));
        assertEquals("AUTOINCREMENT", sqlite.generatedClause());
        assertTrue(sqlite.generatedPrimaryKeyInline());
        assertFalse(sqlite.alterAddColumnNotNull());
        assertEquals("TEXT", sqlite.defaultUUIDType());
        assertEquals("TEXT", sqlite.defaultInstantType());
        assertEquals("BLOB", sqlite.defaultBinaryType());
        assertEquals("INTEGER", sqlite.generatedTypeOverride("BIGINT", Long.class));
    }
}
